/* eslint-disable no-unused-vars */
// Festival data – 2026 season
const FESTIVALS = [
    {
        id: 1,
        name: "Rock am Ring",
        location: "Mendig, Rheinland-Pfalz",
        lat: 50.3674,
        lng: 7.3156,
        startDate: "2026-05-29",
        endDate: "2026-05-31",
        genres: ["Rock", "Metal", "Alternative"],
        description: "Eines der größten Open-Air-Rockfestivals Deutschlands – drei Tage voller Rockmusik direkt am Nürburgring.",
        website: "https://www.rock-am-ring.com",
        price: "ab 179 €"
    },
    {
        id: 2,
        name: "Wacken Open Air",
        location: "Wacken, Schleswig-Holstein",
        lat: 54.0014,
        lng: 9.3511,
        startDate: "2026-07-30",
        endDate: "2026-08-01",
        genres: ["Metal"],
        description: "Das weltweit größte Heavy Metal Festival in der kleinen Gemeinde Wacken – ein Pflichttermin für Metalheads.",
        website: "https://www.wacken.com",
        price: "ab 220 €"
    },
    {
        id: 3,
        name: "Hurricane Festival",
        location: "Scheeßel, Niedersachsen",
        lat: 53.1639,
        lng: 9.4833,
        startDate: "2026-06-19",
        endDate: "2026-06-21",
        genres: ["Rock", "Alternative", "Pop", "Indie"],
        description: "Eines der beliebtesten Musikfestivals Norddeutschlands mit einem breiten Mix aus Rock, Pop und mehr.",
        website: "https://www.hurricane.de",
        price: "ab 169 €"
    },
    {
        id: 4,
        name: "Southside Festival",
        location: "Neuhausen ob Eck, Baden-Württemberg",
        lat: 47.9833,
        lng: 8.9000,
        startDate: "2026-06-19",
        endDate: "2026-06-21",
        genres: ["Rock", "Alternative", "Pop", "Indie"],
        description: "Das Schwesternevent des Hurricane Festivals – dasselbe Line-up, diesmal im sonnigen Süden Deutschlands.",
        website: "https://www.southside.de",
        price: "ab 169 €"
    },
    {
        id: 5,
        name: "Lollapalooza Berlin",
        location: "Berlin",
        lat: 52.5163,
        lng: 13.3777,
        startDate: "2026-09-12",
        endDate: "2026-09-13",
        genres: ["Pop", "Alternative", "Electronic", "Hip-Hop"],
        description: "Internationales Kultfestival im Berliner Olympiapark mit großer Lineup-Vielfalt aus aller Welt.",
        website: "https://www.lollapaloozade.com",
        price: "ab 149 €"
    },
    {
        id: 6,
        name: "Melt Festival",
        location: "Ferropolis, Sachsen-Anhalt",
        lat: 51.7167,
        lng: 12.2333,
        startDate: "2026-07-17",
        endDate: "2026-07-19",
        genres: ["Electronic", "Alternative", "Indie"],
        description: "Einzigartiges Festival auf dem Gelände der Industrieruine Ferropolis – Electronic und Alternative in atemberaubender Kulisse.",
        website: "https://www.meltfestival.de",
        price: "ab 129 €"
    },
    {
        id: 7,
        name: "Parookaville",
        location: "Weeze, Nordrhein-Westfalen",
        lat: 51.5972,
        lng: 6.1611,
        startDate: "2026-07-17",
        endDate: "2026-07-19",
        genres: ["Electronic", "EDM", "House"],
        description: "Die legendäre 'Stadt der Träume' – eines der größten EDM-Festivals Europas auf dem ehemaligen Flughafen Weeze.",
        website: "https://www.parookaville.com",
        price: "ab 169 €"
    },
    {
        id: 8,
        name: "Open Flair Festival",
        location: "Eschwege, Hessen",
        lat: 51.1834,
        lng: 10.0530,
        startDate: "2026-08-05",
        endDate: "2026-08-09",
        genres: ["Indie", "Alternative", "Folk"],
        description: "Gemütliches Festival mit Indie-, Alternative- und Folk-Musik direkt an der Werra – familiäre Atmosphäre garantiert.",
        website: "https://www.open-flair.de",
        price: "ab 109 €"
    },
    {
        id: 9,
        name: "Nature One",
        location: "Kastellaun, Rheinland-Pfalz",
        lat: 50.0641,
        lng: 7.4439,
        startDate: "2026-08-07",
        endDate: "2026-08-09",
        genres: ["Electronic", "Techno"],
        description: "Europas größtes Outdoor-Technofestival auf einem ehemaligen US-Militärgelände in der Rheinpfalz.",
        website: "https://www.nature-one.de",
        price: "ab 119 €"
    },
    {
        id: 10,
        name: "Deichbrand Festival",
        location: "Cuxhaven, Niedersachsen",
        lat: 53.8693,
        lng: 8.6957,
        startDate: "2026-07-16",
        endDate: "2026-07-19",
        genres: ["Rock", "Pop", "Alternative", "Hip-Hop"],
        description: "Das Nordseefestival mit breitem Musikmix direkt an der Küste – Meeresluft inklusive.",
        website: "https://www.deichbrand.de",
        price: "ab 139 €"
    },
    {
        id: 11,
        name: "Fusion Festival",
        location: "Lärz, Mecklenburg-Vorpommern",
        lat: 53.3667,
        lng: 12.7333,
        startDate: "2026-06-24",
        endDate: "2026-06-29",
        genres: ["Electronic", "Techno"],
        description: "Einzigartiges Kultur- und Musikfestival auf einem ehemaligen Militärflughafen – ohne Werbung, ohne Sponsoring, mit viel Herzblut.",
        website: "https://www.fusion-festival.de",
        price: "Kulturkostenbeitrag ~60 €"
    },
    {
        id: 12,
        name: "Reeperbahn Festival",
        location: "Hamburg",
        lat: 53.5500,
        lng: 9.9667,
        startDate: "2026-09-23",
        endDate: "2026-09-26",
        genres: ["Indie", "Pop", "Alternative", "Electronic"],
        description: "Europas größtes Club-Festival auf dem Hamburger Kiez – über 600 Konzerte in vier Tagen.",
        website: "https://www.reeperbahnfestival.com",
        price: "ab 79 €"
    },
    {
        id: 13,
        name: "Summerjam",
        location: "Köln, Nordrhein-Westfalen",
        lat: 50.9969,
        lng: 6.9758,
        startDate: "2026-07-03",
        endDate: "2026-07-05",
        genres: ["Reggae", "Hip-Hop"],
        description: "Das größte Reggae-Festival Europas am Fühlinger See in Köln – Sonne, Musik und gute Vibes.",
        website: "https://www.summerjam.de",
        price: "ab 89 €"
    },
    {
        id: 14,
        name: "Ruhr in Love",
        location: "Oberhausen, Nordrhein-Westfalen",
        lat: 51.4697,
        lng: 6.8527,
        startDate: "2026-06-06",
        endDate: "2026-06-07",
        genres: ["Electronic", "Techno", "House"],
        description: "Eines der größten Outdoor-Technofestivals im Ruhrgebiet – Liebe, Beats und das Ruhrpott-Feeling.",
        website: "https://www.ruhr-in-love.de",
        price: "ab 69 €"
    },
    {
        id: 15,
        name: "Airbeat One",
        location: "Neustadt-Glewe, Mecklenburg-Vorpommern",
        lat: 53.3803,
        lng: 11.5942,
        startDate: "2026-07-08",
        endDate: "2026-07-12",
        genres: ["Electronic", "EDM"],
        description: "Spektakuläres Dance-Music-Festival mit einer Flugzeuglandebahn als Bühnenkulisse – Norddeutschlands Elektronik-Highlight.",
        website: "https://www.airbeat-one.de",
        price: "ab 99 €"
    },
    {
        id: 16,
        name: "Full Force Festival",
        location: "Gräfenhainichen, Sachsen-Anhalt",
        lat: 51.7239,
        lng: 12.3100,
        startDate: "2026-06-19",
        endDate: "2026-06-21",
        genres: ["Metal", "Rock", "Hardcore"],
        description: "Metal- und Hardcore-Festival auf dem Gelände der Ferropolis – für alle, die es hart mögen.",
        website: "https://www.full-force-festival.de",
        price: "ab 99 €"
    },
    {
        id: 17,
        name: "Juicy Beats",
        location: "Dortmund, Nordrhein-Westfalen",
        lat: 51.5096,
        lng: 7.5027,
        startDate: "2026-08-01",
        endDate: "2026-08-02",
        genres: ["Electronic", "Hip-Hop", "Pop", "Alternative"],
        description: "Urban Electro-Pop-Festival im Westfalenpark Dortmund – bunt, vielfältig und mitten in der Stadt.",
        website: "https://www.juicybeats.net",
        price: "ab 49 €"
    },
    {
        id: 18,
        name: "Maifeld Derby",
        location: "Mannheim, Baden-Württemberg",
        lat: 49.4839,
        lng: 8.4711,
        startDate: "2026-08-28",
        endDate: "2026-08-30",
        genres: ["Indie", "Alternative", "Folk"],
        description: "Gemütliches Indie-Festival auf der Pferderennbahn in Mannheim – mit besonderer Atmosphäre und feinem Lineup.",
        website: "https://www.maifeldderby.de",
        price: "ab 89 €"
    },
    {
        id: 19,
        name: "Helene Beach Festival",
        location: "Frankfurt (Oder), Brandenburg",
        lat: 52.3411,
        lng: 14.5561,
        startDate: "2026-08-06",
        endDate: "2026-08-09",
        genres: ["Pop", "Electronic", "Schlager"],
        description: "Partyspaß am Helenesee – Schlager, Pop und Elektronik direkt am Wasser in Brandenburg.",
        website: "https://www.helene-beach-festival.de",
        price: "ab 89 €"
    },
    {
        id: 20,
        name: "c/o pop",
        location: "Köln, Nordrhein-Westfalen",
        lat: 50.9381,
        lng: 6.9592,
        startDate: "2026-08-19",
        endDate: "2026-08-23",
        genres: ["Pop", "Indie", "Electronic", "Alternative"],
        description: "Kölns Popmusik-Convention mit Konzerten in diversen Clubs der ganzen Stadt – Networking und Musik in einem.",
        website: "https://www.copop.de",
        price: "ab 29 €"
    },
    {
        id: 21,
        name: "Highfield Festival",
        location: "Großpösna, Sachsen",
        lat: 51.2539,
        lng: 12.4719,
        startDate: "2026-08-14",
        endDate: "2026-08-16",
        genres: ["Rock", "Alternative", "Indie", "Metal"],
        description: "Ostdeutsches Rockfestival am Störmthaler See bei Leipzig – familiär, leidenschaftlich und seit Jahren ein Geheimtipp.",
        website: "https://www.highfield.de",
        price: "ab 99 €"
    },
    {
        id: 22,
        name: "Kosmonaut Festival",
        location: "Chemnitz, Sachsen",
        lat: 50.8357,
        lng: 12.9226,
        startDate: "2026-07-04",
        endDate: "2026-07-05",
        genres: ["Indie", "Alternative", "Electronic"],
        description: "Indie- und Alternative-Festival mitten in Chemnitz – urban, jung und mit einem besonderen Flair.",
        website: "https://www.kosmonauten.de",
        price: "ab 59 €"
    },
    {
        id: 23,
        name: "Taubertal Festival",
        location: "Rothenburg ob der Tauber, Bayern",
        lat: 49.3806,
        lng: 10.1789,
        startDate: "2026-08-07",
        endDate: "2026-08-09",
        genres: ["Rock", "Alternative", "Pop"],
        description: "Kleines feines Festival in der romantischen Kulisse des Taubertals – überschaubar, herzlich und musikalisch hochwertig.",
        website: "https://www.taubertal-festival.de",
        price: "ab 89 €"
    },
    {
        id: 24,
        name: "Immergut Festival",
        location: "Neustrelitz, Mecklenburg-Vorpommern",
        lat: 53.3556,
        lng: 13.0692,
        startDate: "2026-05-28",
        endDate: "2026-05-30",
        genres: ["Indie", "Folk", "Alternative"],
        description: "Kleines, intimes Indie- und Folk-Festival in Neustrelitz – für alle, die lieber in der zweiten Reihe stehen.",
        website: "https://www.immergutrockt.de",
        price: "ab 79 €"
    },
    {
        id: 25,
        name: "M'era Luna",
        location: "Hildesheim, Niedersachsen",
        lat: 52.1561,
        lng: 9.9514,
        startDate: "2026-08-08",
        endDate: "2026-08-09",
        genres: ["Gothic", "Metal", "Electronic"],
        description: "Europas größtes Gothic- und Dark-Music-Festival auf dem Flughafen Hildesheim – düster, spektakulär und einmalig.",
        website: "https://www.mera-luna.de",
        price: "ab 99 €"
    },
    {
        id: 26,
        name: "Frequency Festival",
        location: "St. Pölten, Österreich",
        lat: 48.1995,
        lng: 15.6225,
        startDate: "2026-08-20",
        endDate: "2026-08-22",
        genres: ["Rock", "Alternative", "Pop", "Electronic"],
        description: "Österreichs größtes Open-Air-Festival direkt an der Traisen – für alle Grenznähe-Fans ein Muss.",
        website: "https://www.frequency.at",
        price: "ab 159 €"
    },
    {
        id: 27,
        name: "Splash! Festival",
        location: "Gräfenhainichen, Sachsen-Anhalt",
        lat: 51.7300,
        lng: 12.2200,
        startDate: "2026-07-10",
        endDate: "2026-07-12",
        genres: ["Hip-Hop"],
        description: "Europas größtes Hip-Hop-Festival auf dem Gelände der Ferropolis – Rap, Beats und HipHop-Kultur.",
        website: "https://www.splash-festival.de",
        price: "ab 109 €"
    },
    {
        id: 28,
        name: "Rocco del Schlacko",
        location: "Püttlingen, Saarland",
        lat: 49.2892,
        lng: 6.8867,
        startDate: "2026-08-13",
        endDate: "2026-08-15",
        genres: ["Rock", "Alternative", "Indie"],
        description: "Kleines, aber feines Indie-Rock-Festival im Saarland – bekannt für sein besonders entspanntes Flair.",
        website: "https://www.roccodelschlacko.de",
        price: "ab 75 €"
    }
];
